locals {
  name_prefix = "${var.project_name}-${var.environment}"
}

# Generated by Terraform, not typed anywhere by a human — this is the
# credential's only origin. It ends up in Terraform state (state is
# encrypted at rest via the bootstrap KMS key) and in Secrets Manager
# (also KMS-encrypted). It is never written to a .tfvars file.
resource "random_password" "db_master" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = "${local.name_prefix}/db-credentials"
  description             = "RDS PostgreSQL master credentials for ${local.name_prefix}"
  recovery_window_in_days = var.recovery_window_in_days

  tags = merge(var.tags, { Name = "${local.name_prefix}-db-credentials" })
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_master.result
  })
}
